<?php

/**
 * @file
 * Contains gdx_analytics_drupal_snowplow.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gdx_analytics_drupal_snowplow_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gdx_analytics_drupal_snowplow module.
    case 'help.page.gdx_analytics_drupal_snowplow':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the GDX Analytics Drupal Snowplow module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function gdx_analytics_drupal_snowplow_page_attachments(array &$page) {
  $config = \Drupal::config('gdx_analytics_drupal_snowplow.settings');
  $collector = $config->getRawData()['gdx_collector_mode'];
  $script_uri = $config->getRawData()['gdx_analytics_snowplow_script_uri'];

  $page['#attached']['drupalSettings']['gdx_collector'] = $collector;
  
  if(Drupal::request()->attributes->get('_title') == 'Search') {
    $page['#attached']['drupalSettings']['search_terms'] = explode(' ', Drupal::request()->query->all()['keys']);
    $page['#attached']['drupalSettings']['script_uri'] = $script_uri;
    $page['#attached']['library'][] = 'gdx_analytics_drupal_snowplow/gdx_analytics_drupal_snowplow.webtracker_search';
  } else {
    $page['#attached']['drupalSettings']['script_uri'] = $script_uri;
    $page['#attached']['library'][] = 'gdx_analytics_drupal_snowplow/gdx_analytics_drupal_snowplow.webtracker'; 
  }
}
